config/routes.rb
Rails.application.routes.draw do

  get "tasks", to: "tasks#index"
  get "tasks/:id", to: "tasks#show", as: :task

  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy", as: :destroy_restaurant

   # R# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :fetch_task, except: [:index, :new, :create, :show]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    Task.new(params_task)
    redirect_to tasks_path(@tasks)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task.update(params[:task])
    redirect_to tasks_path(@task)
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    # redirect_to tasks_path(@tasks)
  end

  private

  def fetch_task
    @task = Task.find(params[:id])
  end

  def params_task
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Editting <%= @task.name %></h1>

<%= form_for(@tasks) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= link_to "Edit", tasks_path %>

app/views/tasks/index.html.erb
<h1>List of tasks</h1>

<%= link_to "Add a task", tasks_new_path %>

<% @tasks.each do |task| %>
<%= task.name %><br><%= link_to "Delete", task_path(task), method: :delete %>
<%= link_to "Edit", task_path(task), method: :patch %><br>
<% end %>

app/views/tasks/new.html.erb
<h1>Create new task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task selected</h1>
<h2><%= @task.name %></h2>

<%= link_to "Task List", tasks_path %>